### ISSUE TITLE
Add support for iTerm2 for -f option

### ISSUE THREAD

**Issue by plaetzchen** [variadico/noti#13]
When using the -f option with iTerm2 not iTerm will be put in the foreground but the Terminal will be launched.

**Comment by variadico** [comment]
I hope I didn't totally just kill your entire workflow... but...

`-f` has been removed in v2. https://github.com/variadico/noti/blob/master/CHANGELOG.md

I took it out because it was buggy, unpredictable, and made the code simpler. In its place, I was trying to get native `NSUserNotification`s to work like any other app. Ideally, you would be able to click on the notification and it should take you to Terminal.app or iTerm2.app. But, right now that doesn't quite work. I'm not really an Objective-C dev, so I'll need some help or just more time to debug this.

Sorry. :(

#15
