### ISSUE TITLE
Get error when installing with go get

### ISSUE THREAD

**Issue by nikitavoloboev** [variadico/noti#79]
Omit non-relevant sections.

#### Description
What is this issue about?
Get error when installing with go get

#### Use case
What use case would this solve?

#### Steps to reproduce
What steps did you take when you found this issue?
Ran: `go get -u github.com/variadico/noti/cmd/noti`

#### Expected behavior
What did you expect to happen?
It installs.

#### Actual behavior
What actually happened?
Got this:
```bash
❯ go get -u github.com/variadico/noti/cmd/noti
# cd .; git clone https://github.com/variadico/noti /Users/nikivi/go/src/github.com/variadico/noti
Cloning into '/Users/nikivi/go/src/github.com/variadico/noti'...
fatal: unable to access 'https://github.com/variadico/noti/': error setting certificate verify locations:
  CAfile: /etc/ssl/cert.pem
  CApath: none
package github.com/variadico/noti/cmd/noti: exit status 128

```

#### Version
What `go version` and `noti --version` are you using?
`go version go1.10.1 darwin/amd64`

**Comment by variadico** [comment]
Sorry for the late response!

`go get` installation is currently broken in Go 1.12. I'm actually removing `go get` as a supported installation method until the modules team fixes some issues.

Issues that impact noti:

* https://github.com/golang/go/issues/27227
* https://github.com/golang/go/issues/32502

Sorry.

If you need a binary, just download one from the releases page.
https://github.com/variadico/noti/releases

Otherwise, you can `git clone` and build with `make build` if you need to compile from source.

Closing the ticket for now. Thanks!
